name: formxls
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.11.0

dependencies:
  file_picker: ^8.1.2
  flutter:
    sdk: flutter
  chaquopy: any
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  # PACOTES PARA ÍCONE E SPLASH SCREEN ALINHADOS CORRETAMENTE
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.4.0

# --------------------------------------------------------
# CONFIGURAÇÃO DO ÍCONE (Mesmo logo para tudo)
# --------------------------------------------------------
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logo.png"
  web:
    generate: true
    image_path: "assets/logo.png"
  windows:
    generate: true
    image_path: "assets/logo.png"

# --------------------------------------------------------
# CONFIGURAÇÃO DA TELA DE CARREGAMENTO (Splash Screen)
# --------------------------------------------------------
flutter_native_splash:
  color: "#ffffff" # Cor do fundo (branco). Você pode mudar o HEX se quiser.
  image: "assets/logo.png"
  android_12:
    image: "assets/logo.png"

flutter:
  uses-material-design: true
  
  # Declaração da pasta assets para o app poder ler a imagem
  assets:
    - assets/logo.png